---
- name: Ensure cAdvisor is started
  docker_container:
    name: cadvisor
    image: google/cadvisor:latest
    restart_policy: always
    memory: 512m
    labels:
      namespace: management
    ports:
      - "{{ docker_metrics_port }}:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "{{ docker_directory_path }}:/var/lib/docker:ro"
      - "/etc/localtime:/etc/localtime:ro"
    log_driver: syslog
    log_options:
      syslog-facility: local0
      tag: cadvisor
