---
- name: Ensure directory exists
  file:
    path: "/etc/telegraf/telegraf.d"
    state: directory

- name: Create telegraf plugin config
  template:
    src: docker_telegraf.conf.j2
    dest: /etc/telegraf/telegraf.d/docker.conf

- name: Ensure telegraf user is in docker group
  user:
    name: telegraf
    system: yes
    createhome: no
    shell: /bin/false
    groups: docker

  
